debug: false
spring:
  profiles:
    active: cli

  main:
    web-environment: false
    banner-mode: "off"

logging.file: application-debug.log
logging.level:
  root: INFO
logging:
  file:
    max-size: 20 MB



